<?php
get_header();
get_template_part('template-parts/hero');
get_template_part('template-parts/about');
get_template_part('template-parts/services');
get_template_part('template-parts/treningi');
get_template_part('template-parts/instructors');
get_template_part('template-parts/hippotherapy');
get_template_part('template-parts/boarding');
get_template_part('template-parts/events');
get_footer();
?>